models/User.php
<?php

namespace app\models;

use Ramsey\Uuid\Uuid;
use Yii;
use yii\base\Exception;
use yii\db\ActiveQuery;
use yii\db\ActiveRecord;

/**
 * This is the model class for table "{{%user}}".
 *
 * @property string $id
 * @property string $username
 * @property string $password_hash
 * @property string $first_name
 * @property string $last_name
 * @property int $genre_id
 * @property string $created_time
 * @property string $email
 *
 * @property string $password
 * @property string $confirm_password
 *
 * @property ShippingAddress[] $shippingAddresses
 */
class User extends ActiveRecord
{
    const GENRE_MALE = 1;
    const GENRE_FEMALE = 2;
    const GENRE_NO_INFORMATION = 3;

    public $password;
    public $confirm_password;

    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return '{{%user}}';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['id', 'username', 'password_hash', 'first_name', 'last_name', 'email', 'genre_id', 'created_time'], 'required'],
            [['id'], 'unique'],
            [['id'], 'string'],
            [['created_time'], 'safe'],

            [['first_name', 'last_name'], 'string', 'max' => 255],
            [['first_name', 'last_name'], 'match', 'pattern' => '/[A-Z]{1}[a-z]+/', 'message' => 'You can only use latin letters starting with a capital letter.'],

            ['genre_id', 'in', 'range' => [self::GENRE_MALE, self::GENRE_FEMALE, self::GENRE_NO_INFORMATION]],
            [['genre_id'], 'integer'],

            ['username', 'string', 'min' => 4],
            ['username', 'unique', 'targetClass' => '\app\models\User', 'message' => 'This username has already been taken.'],

            [['email'], 'email'],
            ['email', 'unique', 'targetClass' => '\app\models\User', 'message' => 'This email has already been taken.'],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'username' => 'Username',
            'password' => 'Password',
            'confirm_password' => 'Confirm Password',
            'first_name' => 'First Name',
            'last_name' => 'Last Name',
            'genre_id' => 'Genre',
            'created_time' => 'Created Time',
            'email' => 'Email',
        ];
    }

    /**
     * @return ActiveQuery
     */
    public function getShippingAddresses()
    {
        return $this->hasMany(ShippingAddress::class, ['user_id' => 'id']);
    }

    /**
     * Generates password hash from password and sets it to the model
     *
     * @param string $password
     * @throws Exception
     */
    public function setPassword($password)
    {
        $this->password_hash = Yii::$app->security->generatePasswordHash($password);
    }

    /**
     * @return bool|null
     * @throws Exception
     * @throws \Exception
     */
    public function create()
    {
        if (!$this->validate()) {
            return null;
        }

        $this->id = Uuid::uuid4()->toString();
        $this->created_time = date('d-m-Y H:i:s');
        $this->password_hash = $this->setPassword($this->password);
        $this->setPassword($this->password);
        return $this->save();
    }

    /**
     * @return string
     */
    public function getGenre()
    {
        if ($this->genre_id === 1) {
            return 'Male';
        } elseif ($this->genre_id === 2) {
            return 'Female';
        } else {
            return 'No information';
        }
    }
}

controllers/ShippingAddressController.php
<?php

namespace app\controllers;

use app\repositories\ShippingAddressRepository;
use app\models\ShippingAddress;
use app\models\ShippingAddressSearch;
use app\repositories\UserRepository;
use Exception;
use yii\db\StaleObjectException;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use Throwable;
use Yii;

/**
 * ShippingAddressController implements the CRUD actions for ShippingAddress model.
 */
class ShippingAddressController extends BaseController
{
    /* @var ShippingAddress */
    private $shippingAddress;
    /* @var ShippingAddressRepository */
    private $shippingAddressRepository;
    /* @var ShippingAddressSearch */
    private $shippingAddressSearch;
    /* @var UserRepository */
    private $userRepository;

    /**
     * ShippingAddressController constructor.
     * {@inheritdoc}
     * @param ShippingAddress $shippingAddress
     * @param ShippingAddressRepository $shippingAddressRepository
     * @param ShippingAddressSearch $shippingAddressSearch
     */
    public function __construct(
        $id,
        $module,
        ShippingAddress $shippingAddress,
        ShippingAddressRepository $shippingAddressRepository,
        ShippingAddressSearch $shippingAddressSearch,
        UserRepository $userRepository,
        $config = []
    )
    {
        $this->shippingAddress = $shippingAddress;
        $this->shippingAddressRepository = $shippingAddressRepository;
        $this->shippingAddressSearch = $shippingAddressSearch;
        $this->userRepository = $userRepository;
        parent::__construct($id, $module, $config);
    }

    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::class,
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Creates a new ShippingAddress model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     * @throws NotFoundHttpException
     * @throws Exception
     */
    public function actionCreate()
    {
        if ($this->shippingAddress->load(Yii::$app->request->post()) && $this->shippingAddress->save()) {
            Yii::$app->session->setFlash('success', 'Shipping address successfully created.');
            return $this->redirect(['/user/view', 'id' => Yii::$app->request->get('id')]);
        }

        return $this->render('create', [
            'model' => $this->shippingAddress,
            'user' => $this->userRepository->findUserById(Yii::$app->request->get('id')),
        ]);
    }

    /**
     * Updates an existing ShippingAddress model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param string $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     * @throws Exception
     */
    public function actionUpdate($id)
    {
        $model = $this->shippingAddressRepository->findShippingAddressById($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            Yii::$app->session->setFlash('success', 'Shipping address successfully updated.');
            return $this->redirect(['/user/view', 'id' => $model->user_id]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing ShippingAddress model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param string $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     * @throws Throwable
     * @throws StaleObjectException
     */
    public function actionDelete($id)
    {
        $model = $this->shippingAddressRepository->findShippingAddressById($id);
        $model->delete();
        Yii::$app->session->setFlash('success', 'Shipping address successfully deleted.');

        return $this->redirect(['/user/view', 'id' => $model->user_id]);
    }
}

controllers/UserController.php
<?php

namespace app\controllers;

use app\models\NewUserForm;
use app\models\ShippingAddress;
use app\models\ShippingAddressSearch;
use app\repositories\UserRepository;
use app\models\User;
use app\models\UserSearch;
use yii\db\StaleObjectException;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use Exception;
use Throwable;
use Yii;

/**
 * UserController implements the CRUD actions for User model.
 */
class UserController extends BaseController
{
    /* @var User */
    private $user;
    /* @var ShippingAddress */
    private $shippingAddress;
    /* @var NewUserForm */
    private $newUserForm;
    /* @var UserSearch */
    private $userSearch;
    /* @var UserRepository */
    private $userRepository;
    /* @var ShippingAddressSearch */
    private $shippingAddressSearch;

    /**
     * UserController constructor.
     * {@inheritdoc}
     * @param User $user
     * @param UserRepository $userRepository
     * @param UserSearch $userSearch
     */
    public function __construct(
        $id,
        $module,
        User $user,
        ShippingAddress $shippingAddress,
        NewUserForm $newUserForm,
        UserRepository $userRepository,
        UserSearch $userSearch,
        ShippingAddressSearch $shippingAddressSearch,
        $config = []
    )
    {
        $this->user = $user;
        $this->shippingAddress = $shippingAddress;
        $this->newUserForm = $newUserForm;
        $this->userRepository = $userRepository;
        $this->userSearch = $userSearch;
        $this->shippingAddressSearch = $shippingAddressSearch;
        parent::__construct($id, $module, $config);
    }

    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::class,
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all User models.
     * @return mixed
     */
    public function actionIndex()
    {
        return $this->render('index', [
            'searchModel' => $this->userSearch,
            'dataProvider' => $this->userSearch->search(Yii::$app->request->queryParams),
        ]);
    }

    /**
     * Displays a single User model.
     * @param string $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        $model = $this->userRepository->findUserById($id);
        $dataProvider = $this->shippingAddressSearch->search($model->id, Yii::$app->request->queryParams);

        return $this->render('view', [
            'model' => $model,
            'dataProvider' => $dataProvider,
            'genre' => $model->getGenre(),
        ]);
    }

    /**
     * Creates a new User model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     * @throws Exception
     */
    public function actionCreate()
    {
        if ($this->newUserForm->load(Yii::$app->request->post()) && $this->newUserForm->create()) {
            Yii::$app->session->setFlash('success', 'User successfully created.');
            return $this->redirect(['/user/index']);
        }

        return $this->render('create', [
            'model' => $this->newUserForm,
        ]);
    }

    /**
     * Updates an existing User model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param string $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->userRepository->findUserById($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            Yii::$app->session->setFlash('success', 'User successfully updated.');
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing User model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param string $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     * @throws Throwable
     * @throws StaleObjectException
     */
    public function actionDelete($id)
    {
        $this->userRepository->findUserById($id)->delete();
        Yii::$app->session->setFlash('success', 'User successfully deleted.');

        return $this->redirect(['/user/index']);
    }
}

views/user/create.php
<?php

use app\models\NewUserForm;
use app\models\User;
use yii\helpers\Html;
use yii\web\View;
use yii\widgets\ActiveForm;

/* @var $this View */
/* @var $model NewUserForm */

$this->title = 'Create User';
$this->params['breadcrumbs'][] = ['label' => 'Users', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>

<div class="user-create">

    <div class="row">

        <div class="col-lg-1"></div>

        <?php $form = ActiveForm::begin(['options' => ['tag' => false]]); ?>

        <div class="col-lg-5">

            <h2><?php echo Html::encode('User information') ?></h2>
            <hr>

            <?php echo $form
                ->field($model, 'first_name')
                ->textInput(
                    [
                        'maxlength' => true,
                        'placeholder' => 'Your first name...',
                    ])
            ?>

            <?php echo $form
                ->field($model, 'last_name')
                ->textInput(
                    [
                        'maxlength' => true,
                        'placeholder' => 'Your last name...',
                    ])
            ?>

            <?php echo $form
                ->field($model, 'genre')
                ->dropDownList(
                    [
                        User::GENRE_MALE => 'Male',
                        User::GENRE_FEMALE => 'Female',
                        User::GENRE_NO_INFORMATION => 'No information',
                    ],
                    ['prompt' => 'Select genre...'])
            ?>

            <?php echo $form
                ->field($model, 'username')
                ->textInput(
                    [
                        'maxlength' => true,
                        'placeholder' => 'Your username...',
                    ])
            ?>

            <?php echo $form
                ->field($model, 'email')
                ->textInput(
                    [
                        'maxlength' => true,
                        'placeholder' => 'Your email...',
                    ])
            ?>

            <?php echo $form
                ->field($model, 'password')
                ->passwordInput(['placeholder' => 'Your password...'])
            ?>

            <?php echo $form
                ->field($model, 'confirm_password')
                ->passwordInput(['placeholder' => 'Confirm password...'])
            ?>

        </div>
        <div class="col-lg-5">

            <h2><?php echo Html::encode('Shipping address information') ?></h2>
            <hr>

            <?php echo $form
                ->field($model, 'zip_code')
                ->textInput(
                    [
                        'maxlength' => true,
                        'placeholder' => 'Your zip code...',
                    ])
            ?>

            <?php echo $form
                ->field($model, 'country')
                ->textInput(
                    [
                        'maxlength' => true,
                        'placeholder' => 'Your country code...',
                    ])
            ?>

            <?php echo $form
                ->field($model, 'city')
                ->textInput(
                    [
                        'maxlength' => true,
                        'placeholder' => 'Your city...',
                    ])
            ?>

            <?php echo $form
                ->field($model, 'street')
                ->textInput(
                    [
                        'maxlength' => true,
                        'placeholder' => 'Your street...',
                    ])
            ?>

            <?php echo $form
                ->field($model, 'house_number')
                ->textInput(['placeholder' => 'Your house number...']) ?>

            <?php echo $form
                ->field($model, 'flat_number')
                ->textInput(['placeholder' => 'Your flat/office number...']) ?>

        </div>

        <div class="col-lg-1" style="clear: both"></div>

        <div class="col-lg-10">

            <?php echo Html::submitButton('Save', ['class' => 'btn btn-large btn-block btn-success']) ?>

        </div>

        <?php ActiveForm::end(); ?>

    </div>

</div>

views/user/index.php
<?php

use app\models\UserSearch;
use yii\data\ActiveDataProvider;
use yii\grid\GridView;
use yii\web\View;

/* @var $this View */
/* @var $searchModel UserSearch */
/* @var $dataProvider ActiveDataProvider */

$this->title = 'Users';
$this->params['breadcrumbs'][] = $this->title;
?>

<div class="user-index">

    <div class="row">

        <?php echo $this->render('search-form', ['model' => $searchModel]); ?>

        <?php echo GridView::widget([
            'dataProvider' => $dataProvider,
            'columns' => [
                ['class' => 'yii\grid\SerialColumn'],
                'first_name',
                'last_name',
                'username',
                'created_time:datetime',
                'email:email',
                ['class' => 'yii\grid\ActionColumn'],
            ],
            'pager' => [
                'prevPageLabel' => 'Previous',
                'nextPageLabel' => 'Next',
            ],
            'tableOptions' => ['class' => 'table table-hover'],
            'options' => [
                'class' => 'col-lg-9',
            ],
        ]); ?>

    </div>

</div>

views/user/search-form.php
<?php

use app\models\User;
use app\models\UserSearch;
use kartik\datetime\DateTimePicker;
use yii\helpers\Html;
use yii\web\View;
use yii\widgets\ActiveForm;

/* @var $this View */
/* @var $model UserSearch */
/* @var $form ActiveForm */
?>

<div class="user-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
        'options' => [
            'class' => 'col-lg-3',
        ],
    ]); ?>

    <?php echo $form->field($model, 'searchName') ?>

    <?php echo $form
        ->field($model, 'genre_id')
        ->dropDownList(
            [
                User::GENRE_MALE => 'Male',
                User::GENRE_FEMALE => 'Female',
                User::GENRE_NO_INFORMATION => 'No information',
            ],
            [
                'prompt' => 'Select genre...',
            ]
        ) ?>

    <?php echo $form
        ->field($model, 'createdFrom')
        ->widget(DateTimePicker::class,
            [
                'pluginOptions' => [
                    'format' => 'dd-mm-yyyy hh:ii',
                    'autoclose' => true,
                    'weekStart' => 1,
                    'todayBtn' => true,
                ]
            ]
        ) ?>

    <?php echo $form
        ->field($model, 'createdTo')
        ->widget(DateTimePicker::class,
            [
                'pluginOptions' => [
                    'format' => 'dd-mm-yyyy hh:ii',
                    'autoclose' => true,
                    'weekStart' => 1,
                    'todayBtn' => true,
                ]
            ]
        ) ?>

    <?php // echo $form->field($model, 'email') ?>

    <div class="form-group">
        <?php echo Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?php echo Html::resetButton('Reset', ['class' => 'btn btn-outline-secondary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/user/update.php
<?php

use app\models\User;
use yii\helpers\Html;
use yii\web\View;
use yii\widgets\ActiveForm;

/* @var $this View */
/* @var $model User */

$this->title = 'Update User: ' . $model->username;
$this->params['breadcrumbs'][] = ['label' => 'Users', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->username, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Update';
?>

<div class="user-update">

    <h1><?php echo Html::encode($this->title) ?></h1>

    <div class="row">

        <div class="col-lg-5">

            <?php $form = ActiveForm::begin(['options' => ['class' => 'form-horizontal']]); ?>

            <?php echo $form->field($model, 'first_name')->textInput(['maxlength' => true]) ?>

            <?php echo $form->field($model, 'last_name')->textInput(['maxlength' => true]) ?>

            <?php echo $form->field($model, 'genre_id')->dropDownList(
                [
                    User::GENRE_MALE => 'Male',
                    User::GENRE_FEMALE => 'Female',
                    User::GENRE_NO_INFORMATION => 'No information',
                ],
                [
                    'prompt' => 'Select genre...',
                ]) ?>

            <?php echo $form->field($model, 'username')->textInput(['maxlength' => true]) ?>

            <?php echo $form->field($model, 'email')->textInput([
                    'maxlength' => true,
                    'placeholder' => 'Your email...',
                ]
            ) ?>

            <div class="form-group">
                <?php echo Html::submitButton('Save', ['class' => 'btn btn-success']) ?>
            </div>

            <?php ActiveForm::end(); ?>

        </div>

    </div>

</div>

views/user/view.php
<?php

use app\models\ShippingAddress;
use app\models\ShippingAddressSearch;
use app\models\User;
use yii\data\ActiveDataProvider;
use yii\helpers\Html;
use yii\web\View;
use yii\web\YiiAsset;
use yii\widgets\DetailView;
use yii\widgets\ListView;

/* @var $this View */
/* @var $model User */
/* @var $searchModel ShippingAddressSearch */
/* @var $dataProvider ActiveDataProvider */
/* @var $genre string */

$this->title = $model->username;
$this->params['breadcrumbs'][] = ['label' => 'Users', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
YiiAsset::register($this);
?>

<div class="user-view">

    <h1><?php echo Html::encode($model->first_name . ' ' . $model->last_name) ?></h1>

    <p>
        <?php echo Html::a('Update', ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        <?php echo Html::a('Delete', ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Are you sure you want to delete this item?',
                'method' => 'post',
            ],
        ]) ?>
        <?php echo Html::a('Create Shipping Address', ['/shipping-address/create', 'id' => $model->id], ['class' => 'btn btn-success']) ?>
    </p>

    <dl class="dl-horizontal">

        <?php echo DetailView::widget([
            'model' => $model,
            'attributes' => [
                'id',
                'username',
                'first_name',
                'last_name',
                [
                    'label' => 'Genre',
                    'value' => $genre,
                ],
                'created_time:datetime',
                'email:email',
            ],
            'template' => '<dt{captionOptions}>{label}</dt><dd{contentOptions}>{value}</dd>',
        ]) ?>

    </dl>


    <div class="row">
        <ul class="thumbnails">

            <?php echo ListView::widget([
                'options' => [
                    'class' => 'listing-products',
                    'tag' => false,
                ],
                'dataProvider' => $dataProvider,
                'emptyText' => 'Shipping addresses not found.',
                'itemView' => function ($model, $key, $index, $widget) {
                    /* @var $model ShippingAddress */
                    echo '<li class="col-lg-4" style="list-style-type: none;">';
                    echo '<div class="thumbnail">';
                    echo '<div class="caption">';
                    echo '<h3>Shipping address</h3>';
                    echo DetailView::widget([
                        'model' => $model,
                        'attributes' => [
                            'zip_code',
                            'country',
                            'city',
                            'street',
                            'house_number',
                            'flat_number',
                        ],
                        'template' => '<p{captionOptions}><strong>{label}: </strong>{value}</p><p></p>',
                    ]);
                    echo Html::a('Update', [
                            '/shipping-address/update',
                            'id' => $model->id,
                        ], ['class' => 'btn btn-primary']) . ' ';
                    echo Html::a('Delete', [
                        '/shipping-address/delete',
                        'id' => $model->id,
                    ], [
                        'class' => 'btn btn-danger',
                        'data' => [
                            'confirm' => 'Are you sure you want to delete this item?',
                            'method' => 'post',
                        ],
                    ]);
                    echo '</div></div></li>';
                },
                'layout' => "{items}\n</div><div class=\"container\">{pager}</div>",
                'pager' => [
                    'prevPageLabel' => 'Previous',
                    'nextPageLabel' => 'Next',
                ],
            ]) ?>

        </ul>
    </div>

</div>